export interface User {
  id: number
  username: string
  address: string
  role: string
}

export const users: User[] = [
  {
    id: 1,
    username: 'cattrill0',
    address: '710 Banding Junction',
    role: 'Engineer',
  },
  {
    id: 2,
    username: 'mhunnam1',
    address: '1715 Norway Maple Way',
    role: 'Subcontractor',
  },
  {
    id: 3,
    username: 'brollo2',
    address: '979 Canary Avenue',
    role: 'Engineer',
  },
  {
    id: 4,
    username: 'droscow3',
    address: '50 Pine View Hill',
    role: 'Electrician',
  },
  {
    id: 5,
    username: 'dhirsthouse4',
    address: '6457 Park Meadow Circle',
    role: 'Construction Manager',
  },
  {
    id: 6,
    username: 'mclaiden5',
    address: '124 Brickson Park Circle',
    role: 'Construction Manager',
  },
  {
    id: 7,
    username: 'hbarstowk6',
    address: '653 Bluestem Park',
    role: 'Project Manager',
  },
  {
    id: 8,
    username: 'dbohler7',
    address: '26 Daystar Pass',
    role: 'Construction Foreman',
  },
  {
    id: 9,
    username: 'miverson8',
    address: '9110 Bartelt Parkway',
    role: 'Construction Manager',
  },
  {
    id: 10,
    username: 'ldenacamp9',
    address: '1 North Way',
    role: 'Construction Manager',
  },
  {
    id: 11,
    username: 'rblackborowa',
    address: '8 Eagle Crest Circle',
    role: 'Surveyor',
  },
  {
    id: 12,
    username: 'cscantleberryb',
    address: '694 Valley Edge Terrace',
    role: 'Subcontractor',
  },
  {
    id: 13,
    username: 'bbayfieldc',
    address: '4839 Bunting Pass',
    role: 'Engineer',
  },
  {
    id: 14,
    username: 'lreddingtond',
    address: '0846 Dexter Lane',
    role: 'Construction Manager',
  },
  {
    id: 15,
    username: 'wjearume',
    address: '84447 Toban Court',
    role: 'Estimator',
  },
  {
    id: 16,
    username: 'spresideyf',
    address: '478 Oxford Parkway',
    role: 'Subcontractor',
  },
  {
    id: 17,
    username: 'jthundercliffeg',
    address: '8541 Summerview Parkway',
    role: 'Electrician',
  },
  {
    id: 18,
    username: 'nkonmannh',
    address: '9 Warrior Trail',
    role: 'Supervisor',
  },
  {
    id: 19,
    username: 'mcusti',
    address: '102 Bluestem Avenue',
    role: 'Electrician',
  },
  {
    id: 20,
    username: 'csmythj',
    address: '88427 Toban Trail',
    role: 'Electrician',
  },
  {
    id: 21,
    username: 'jgrissk',
    address: '58 Bartelt Plaza',
    role: 'Engineer',
  },
  {
    id: 22,
    username: 'cgillmanl',
    address: '295 Debra Park',
    role: 'Construction Worker',
  },
  {
    id: 23,
    username: 'mjanacekm',
    address: '211 Mifflin Court',
    role: 'Subcontractor',
  },
  {
    id: 24,
    username: 'eburnhamn',
    address: '91196 Anniversary Park',
    role: 'Estimator',
  },
  {
    id: 25,
    username: 'mmedlero',
    address: '53888 Stuart Alley',
    role: 'Electrician',
  },
  {
    id: 26,
    username: 'kswetenhamp',
    address: '464 Golf Drive',
    role: 'Project Manager',
  },
  {
    id: 27,
    username: 'mhurcheq',
    address: '833 Golden Leaf Drive',
    role: 'Construction Foreman',
  },
  {
    id: 28,
    username: 'ashipleyr',
    address: '32835 Schurz Terrace',
    role: 'Construction Manager',
  },
  {
    id: 29,
    username: 'brandals',
    address: '2711 Everett Trail',
    role: 'Construction Expeditor',
  },
  {
    id: 30,
    username: 'gmussettt',
    address: '5 Schiller Place',
    role: 'Construction Manager',
  },
  {
    id: 31,
    username: 'pmissenu',
    address: '72849 Northport Avenue',
    role: 'Engineer',
  },
  {
    id: 32,
    username: 'drivallantv',
    address: '642 Springview Street',
    role: 'Construction Expeditor',
  },
  {
    id: 33,
    username: 'oglowaczw',
    address: '74747 Everett Plaza',
    role: 'Construction Foreman',
  },
  {
    id: 34,
    username: 'vgerretsenx',
    address: '3 Eastlawn Pass',
    role: 'Project Manager',
  },
  {
    id: 35,
    username: 'wmattony',
    address: '726 5th Place',
    role: 'Project Manager',
  },
  {
    id: 36,
    username: 'glamertonz',
    address: '48484 Mcbride Road',
    role: 'Surveyor',
  },
  {
    id: 37,
    username: 'ckincaid10',
    address: '949 Evergreen Avenue',
    role: 'Estimator',
  },
  {
    id: 38,
    username: 'dscottesmoor11',
    address: '0 Spaight Junction',
    role: 'Project Manager',
  },
  {
    id: 39,
    username: 'bpaulack12',
    address: '38 Prentice Court',
    role: 'Construction Worker',
  },
  {
    id: 40,
    username: 'fscotcher13',
    address: '2 Bonner Place',
    role: 'Construction Worker',
  },
  {
    id: 41,
    username: 'cgraves14',
    address: '6 Fisk Parkway',
    role: 'Supervisor',
  },
  {
    id: 42,
    username: 'wknutsen15',
    address: '25 Rusk Circle',
    role: 'Project Manager',
  },
  {
    id: 43,
    username: 'yvowdon16',
    address: '971 Oak Alley',
    role: 'Project Manager',
  },
  {
    id: 44,
    username: 'foshiels17',
    address: '61266 Pearson Avenue',
    role: 'Construction Worker',
  },
  {
    id: 45,
    username: 'mpocke18',
    address: '07346 Arrowood Road',
    role: 'Subcontractor',
  },
  {
    id: 46,
    username: 'bdunkerly19',
    address: '65933 Glacier Hill Street',
    role: 'Estimator',
  },
  {
    id: 47,
    username: 'ccalwell1a',
    address: '8219 Gateway Alley',
    role: 'Construction Expeditor',
  },
  {
    id: 48,
    username: 'vesposito1b',
    address: '020 Eggendart Court',
    role: 'Construction Manager',
  },
  {
    id: 49,
    username: 'aoffner1c',
    address: '798 Northridge Road',
    role: 'Supervisor',
  },
  {
    id: 50,
    username: 'ibriton1d',
    address: '534 Iowa Parkway',
    role: 'Project Manager',
  },
]
